@startuml
class Mastermind {
  - codeSecret
  - essais
  - maxEssais
  genererCode()
  demanderEssai()
  verifierEssai()
  afficherResultat()
  jouer()
}

class Joueur {
  - nom
  proposerCode()
}

class Partie {
  - mastermind
  - joueur
  lancer()
}

Partie o-- Mastermind
Partie o-- Joueur
@enduml